excluded:
  - .build
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - all
disabled_rules:
  - anonymous_argument_in_multiline_closure
  - async_without_await # https://github.com/realm/SwiftLint/issues/5082#issuecomment-1609693266
  - balanced_xctest_lifecycle
  - conditional_returns_on_newline
  - contrasted_opening_brace
  - convenience_type
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - file_types_order
  - function_default_parameter_at_end
  - identifier_name
  - legacy_objc_type
  - missing_docs
  - no_empty_block
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - one_declaration_per_file
  - optional_data_string_conversion
  - prefer_nimble
  - prefer_self_in_static_references
  - prefixed_toplevel_constant
  - required_deinit
  - sorted_enum_cases
  - sorted_imports
  - switch_case_on_newline
  - trailing_closure
  - type_contents_order # For SwiftUI body (https://github.com/realm/SwiftLint/issues/3548)
  - unused_parameter
  - vertical_whitespace_between_cases
  - vertical_whitespace_opening_braces
attributes:
  attributes_with_arguments_always_on_line_above: false
  always_on_line_above:
    - "@MainActor"
    - "@Option"
    - "@Suite"
  always_on_same_line:
    - "@ViewBuilder"
    - "@Environment"
    - "@EnvironmentObject"
    - "@Test"
closure_body_length:
    warning: 50
    error: 60
function_body_length: 60
large_tuple: 3
number_separator:
  minimum_length: 5
type_body_length: 400
